Feature branch to master Pull Request - Using Bootstrap project
abouhid/Using-Bootstrap pull request #3
Opened 2020-07-10 16:37 UTC by abouhid

This is the pull request needed for the project to be approved. Thank you!

2020-07-10 18:50 UTC, expjazz requested changes
## Status: [Changes Required]

#### Hey Team! The project looks good, but there are still a few details that we need to improve to get this project approved.

### Navbar

| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/87184349-3bbc6a80-c2be-11ea-90e4-7ba9717aa6fa.png) | ![image](https://user-images.githubusercontent.com/61479648/87184389-4d057700-c2be-11ea-8ece-5c42f3d00597.png) |

- [x] Add the info about the city above the date.
-[optional] Try to add that little red detail by the end of the let part of the navbar. You can use css pseudo-elements.

- [x] The navbar needs to stay fixed when you scroll down the page. Please do that as well in your clone. 

- [x] Some elements in the navbar are creating a second row in the mobile version. Kindly fix that.
![image](https://user-images.githubusercontent.com/61479648/87184867-25fb7500-c2bf-11ea-833c-3f6e6009e90c.png)

### Main section

- [x] In the mobile version, sometimes the blue background shows up between sections. 

| Original | Yours |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/87185105-8f7b8380-c2bf-11ea-9e5f-473df479e08b.png) | ![image](https://user-images.githubusercontent.com/61479648/87185179-b1750600-c2bf-11ea-9f00-1d532dd86a5f.png) |

### More Stories

- [ ] The text should wrap below the images when the content is big enough.

| Yours | Original |
|:---:|:---:| 
| ![image](https://user-images.githubusercontent.com/61479648/87185564-5bed2900-c2c0-11ea-9187-4672c94aefaa.png)  | ![image](https://user-images.githubusercontent.com/61479648/87185424-221c2280-c2c0-11ea-92a5-7f0e3e7ab6e1.png)  |

### Editor's pick

- [ ] Please re-organize the rows and columns for the large screen sizes.

| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/87186746-65779080-c2c2-11ea-9648-4c99a8bbdd7c.png)  | ![image](https://user-images.githubusercontent.com/61479648/87186887-a2438780-c2c2-11ea-8ade-ef168f5d09e9.png) |

- [x] You are missing a few sections still: US - World - Business - Tech and Science - Culture and sports

![image](https://user-images.githubusercontent.com/61479648/87187156-154cfe00-c2c3-11ea-84d9-c8ee7102eb50.png)

### Subscribe section

- [x] The colors of the buttons is wrong

| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/87187331-63620180-c2c3-11ea-99b3-c45914215132.png) | ![image](https://user-images.githubusercontent.com/61479648/87187374-783e9500-c2c3-11ea-9294-28db6f8c6754.png) |

- [x] In the newsletter section, some elements overflow in your design in the mobile screen sizes.

| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/87187748-12064200-c2c4-11ea-80a5-927628c532b7.png) | ![image](https://user-images.githubusercontent.com/61479648/87187682-f4d17380-c2c3-11ea-9843-6b66995beae3.png) |

### General

- [ ] Please check the padding of the page, font sizes (and when they are bold or not).

#### This is a tough project, and your clone looks really good already. With these implementations above will look even better. You really displayed  knowledge on Bootstrap and the code looks quite good :clap:
### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:

2020-07-10 20:25 UTC, abouhid commented
Thanks for the review, however, I have some things to point out:
1- fixed the navbar issues
2- Added the section separations
3- On my pc here I tried to replicate what was shown in the print screen, but the original website here does not get organized that way. Therefore I am not able to clone what I can not compare my project to.
4- About the colors, I did not clone exactly the same colors on purpose, because the project focuses on applying bootstrap, hence I tried to use css as least as possible. Are you sure I should change all of that?
5- Overlapping fixed

2020-07-10 20:58 UTC, expjazz requested changes
## Status: Changes Required

#### I understand that it shows different on your screen. So these sections are ok to leave like it is now. Can you submit a print screen for the next review? 

But there is still one thing that you did not change:

- [ ] ![screencapture-github-com-abouhid-Using-Bootstrap-pull-3-1594413844496 (1)](https://user-images.githubusercontent.com/61479648/87201548-2bfc5080-c2d5-11ea-96ee-5e88797ab713.png)

And now the fixed navbar is collapsing on mobile screen size. Kindly fix that.

- [ ] ![screencapture-127-0-0-1-5500-index-html-1594414383212 (1)](https://user-images.githubusercontent.com/61479648/87202117-4c78da80-c2d6-11ea-9ff5-38804e01593c.png)


As for the color, you can leave as that if it is a conscient choice. There is one optional change that I will suggest to improve your project even more:
- The height of the fixed navbar could be smaller on the mobile screen size. 

#### As I stated in my first review, the project does look great. You showed a great level of technical skills and attention to detail. 

## Submit the project for a new review once you are ready.

Good Luck and Happy Coding :pray:

P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:

2020-07-10 22:41 UTC, abouhid commented
Oh sorry, I skipped the text/image issue. It is fixed now.
Collapsing navbar fixed
The Editor's Pick was indeed without the col-lg-3 class, fixed it now
Here the printscreen of what appears to me:
![print1](https://user-images.githubusercontent.com/60702127/87208468-345c8780-c2e5-11ea-9af8-2c47daaf7d27.png)
![print2](https://user-images.githubusercontent.com/60702127/87208470-36bee180-c2e5-11ea-83c6-e6ad4f8978f4.png)

Hope everything is correct now for me to move on! Thanks again for the attention!

2020-07-10 23:59 UTC, bertil291utn requested changes
**Status:** Changes requested 🔴  :shipit: ? Not yet

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

Your work is amazing you master it GitHub Flow you have a professional README file. (Check optional [changes](##Optional_changes))

#### Mandatory changes

##### Layout


- [ ] Complete the missing section. You're missing **New Section picks **section below Editors Pick section

![image](https://user-images.githubusercontent.com/24902525/87210777-703f1f00-c2dc-11ea-85ac-3cac416549a6.png)

 ##### CSS

- [ ] **Using the Same Rule Repetitively**, check inline comment[1]

#### Optional changes

[TAKE IN MIND]

- [ ] Don't forget to use meaningful in all your commits messages, to next projects

  - Next time you might try using this template:


  ```
  An unmeaningful title
  - Descriptive messages
  - More meaningful messages
  ```

<img src="https://user-images.githubusercontent.com/24902525/87211081-71248080-c2dd-11ea-9241-75820aa02d3b.png" alt="image" style="zoom:67%;" />

- [ ] Don't forget use a CSS Table of Contents[1]

  Consider this example below:

  ```
  /* Project Meta */
  
  /* reset  */
  
  /* general */
  
  /* typography */
  
  /* grid */
  
  /* header */
  
  /* footer */
  
  /* Page template A */
  
  /* Page template B */
  
  /* Media Queries */
  ```



_[1] [Good and Bad CSS practices](https://speckyboy.com/good-bad-css-practices/)_



<hr>


Guys work in the requested changes above and request code for another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-07-10 23:59 UTC, bertil291utn commented on css/style.css
> +
### Using the Same Rule Repetitively

Use a class instead:
````
.black {color: #000;}

2020-07-11 00:47 UTC, abouhid commented
It was explained on the past review that this section does not appear on my desktop. I changed the css to avoid repetitive css rules.

2020-07-11 01:31 UTC, bertil291utn commented
**Status:** Changes requested 🔴  :shipit: ? Not yet

# Hey @abouhid , you've been doing a great job.

Thanks for your changes but still is not accomplished as the [rules ](https://speckyboy.com/good-bad-css-practices/)

#### Mandatory changes

 ##### CSS

- [ ] **Using the Same Rule Repetitively**[1]

Try to create a class called `.black-text {color: #000;}` then use in each element tag where you need. Example
```
<div class="title black-text">My title</div>
/* Another tag */
<div class="subtitle black-text">
```

_[1] [Good and Bad CSS practices](https://speckyboy.com/good-bad-css-practices/)_



<hr>


Guys work in the requested changes above and request code for another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-07-11 02:11 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 
## Great job guys thank you for making the required changes by the previous TSE.

now you can merge to master your project is approved.

## Happy coding :tophat:

2020-07-11 02:45 UTC, merged